services:
  cloudflare-warp-proxy:
    image: nxdun/cloudflare-warp-proxy
    network_mode: bridge
    ports:
      - 40000:40000
    restart: unless-stopped
    environment:
      - LICENSE= # Use your own key, for example, Zero Trust or Warp+. Do not use WARP Device Keys (2026MAR19).